{ "Title"; "Fun with Dick and Jane",
 "Year": "2005", 
 "Rated": "PG-13", 
 "Released": "21 Dec 2005", 
 "Runtime": "90 min", 
 "Genre": "Comedy, Crime",
  "Director": "Dean Parisot",
   "Writer": "Judd Apatow, Nicholas Stoller, Gerald Gaiser", 
   "Actors": "Jim Carrey, Téa Leoni, Alec Baldwin", 
   "Plot": "When an affluent couple lose all their money following a series of blunders, they turn to a life of crime to make ends meet.",
    "Language": "English, Spanish", 
    "Country": "United States",
     "Awards": "1 win & 7 nominations", 
     "Poster": "https://m.media-amazon.com/images/M/MV5BYTJiMWFiNzgtMDQxZi00NTFiLWE2YjMtNTA5NzY5YzQxZjNjXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
      "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.1/10" }, { "Source": "Rotten Tomatoes", "Value": "29%" }, { "Source": "Metacritic", "Value": "47/100" }], 
      "Metascore": "47",
       "imdbRating": "6.1",
        "imdbVotes": "143,898",
         "imdbID": "tt0369441", 
         "Type": "movie",
          "DVD": "11 Apr 2006",
           "BoxOffice": "$110,332,737",
            "Production": "N/A",
             "Website": "N/A",
              "Response": "True" }